In [1]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file
# data.DataReader?
from bokeh.embed import components
from bokeh.resources import CDN

start=datetime.datetime(2015,11,1)
end=datetime.datetime(2016,3,10)
df=data.DataReader("GOOG","yahoo",start,end)
type(df)

pandas.core.frame.DataFrame

In [2]:
df.index[df["Close"] > df["Open"]]

DatetimeIndex(['2015-11-02', '2015-11-03', '2015-11-04', '2015-11-05',
               '2015-11-06', '2015-11-10', '2015-11-11', '2015-11-12',
               '2015-11-16', '2015-11-18', '2015-11-20', '2015-11-25',
               '2015-11-27', '2015-12-01', '2015-12-04', '2015-12-08',
               '2015-12-14', '2015-12-16', '2015-12-21', '2015-12-28',
               '2015-12-29', '2016-01-06', '2016-01-12', '2016-01-14',
               '2016-01-15', '2016-01-20', '2016-01-21', '2016-01-22',
               '2016-01-28', '2016-01-29', '2016-02-01', '2016-02-08',
               '2016-02-09', '2016-02-11', '2016-02-17', '2016-02-19',
               '2016-02-24', '2016-02-25', '2016-03-01', '2016-03-08',
               '2016-03-09', '2016-03-10'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [3]:
hours_12=43200000 # 12 hours to msec

In [4]:
def inc_dec(c,o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"
    return value

df["Status"]= [inc_dec(c,o) for c,o in zip(df["Close"],df["Open"])]

df["Middle"]=(df["Open"]+df["Close"])/2

df["Height"]=abs(df["Open"]-df["Close"])

In [5]:
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2015-11-02,721.619995,705.849976,711.059998,721.109985,1886300,721.109985,Increase,716.084991,10.049988
2015-11-03,724.650024,714.719971,718.859985,722.159973,1565400,722.159973,Increase,720.509979,3.299988
2015-11-04,733.099976,721.900024,722.000000,728.109985,1706700,728.109985,Increase,725.054993,6.109985
2015-11-05,739.479980,729.469971,729.469971,731.250000,1861600,731.250000,Increase,730.359985,1.780029
2015-11-06,735.409973,727.010010,731.500000,733.760010,1511600,733.760010,Increase,732.630005,2.260010
2015-11-09,734.710022,719.429993,730.200012,724.890015,2069800,724.890015,Decrease,727.545013,5.309998
2015-11-10,730.590027,718.500000,724.400024,728.320007,1608000,728.320007,Increase,726.360016,3.919983
2015-11-11,741.000000,730.229980,732.460022,735.400024,1366400,735.400024,Increase,733.930023,2.940002
2015-11-12,737.799988,728.645020,731.000000,731.229980,1837200,731.229980,Increase,731.114990,0.229980
2015-11-13,731.150024,716.729980,729.169983,717.000000,2075500,717.000000,Decrease,723.084991,12.169983
2015-11-16,729.489990,711.330017,715.599976,728.960022,1905900,728.960022,Increase,722.279999,13.360046
2015-11-17,731.844971,723.026978,729.289978,725.299988,1510900,725.299988,Decrease,727.294983,3.989990
2015-11-18,741.409973,727.000000,727.580017,740.000000,1684300,740.000000,Increase,733.790009,12.419983
2015-11-19,742.000000,737.429993,738.739990,738.409973,1327100,738.409973,Decrease,738.574982,0.330017
2015-11-20,757.919983,743.000000,746.530029,756.599976,2212300,756.599976,Increase,751.565002,10.069946
2015-11-23,762.708008,751.820007,757.450012,755.979980,1414500,755.979980,Decrease,756.714996,1.470032
2015-11-24,755.278992,737.630005,752.000000,748.280029,2333100,748.280029,Decrease,750.140015,3.719971
2015-11-25,752.000000,746.059998,748.140015,748.150024,1122100,748.150024,Increase,748.145020,0.010010
2015-11-27,753.409973,747.489990,748.460022,750.260010,838500,750.260010,Increase,749.360016,1.799988
2015-11-30,754.929993,741.270020,748.809998,742.599976,2097600,742.599976,Decrease,745.704987,6.210022
2015-12-01,768.950012,746.700012,747.109985,767.039978,2134600,767.039978,Increase,757.074982,19.929993
2015-12-02,775.955017,758.960022,768.900024,762.380005,2230400,762.380005,Decrease,765.640015,6.520020
2015-12-03,768.994995,745.630005,766.010010,752.539978,2590600,752.539978,Decrease,759.274994,13.470032
2015-12-04,768.489990,750.000000,753.099976,766.809998,2757300,766.809998,Increase,759.954987,13.710022
2015-12-07,768.729980,755.090027,767.770020,763.250000,1812300,763.250000,Decrease,765.510010,4.520020
2015-12-08,764.799988,754.200012,757.890015,762.369995,1829500,762.369995,Increase,760.130005,4.479980
2015-12-09,764.229980,737.000977,759.169983,751.609985,2700000,751.609985,Decrease,755.389984,7.559998
2015-12-10,755.849976,743.830017,752.849976,749.460022,1988400,749.460022,Decrease,751.154999,3.389954
2015-12-11,745.710022,736.750000,741.159973,738.869995,2224400,738.869995,Decrease,740.014984,2.289978
2015-12-14,748.729980,724.169983,741.789978,747.770020,2412500,747.770020,Increase,744.779999,5.980042
...,...,...,...,...,...,...,...,...,...
2016-01-28,733.690002,712.349976,722.219971,730.960022,2676400,730.960022,Increase,726.589996,8.740051
2016-01-29,744.989990,726.799988,731.530029,742.950012,3474300,742.950012,Increase,737.240021,11.419983
2016-02-01,757.859985,743.270020,750.460022,752.000000,5139200,752.000000,Increase,751.230011,1.539978
2016-02-02,789.869995,764.650024,784.500000,764.650024,6348100,764.650024,Decrease,774.575012,19.849976
2016-02-03,774.500000,720.500000,770.219971,726.950012,6171000,726.950012,Decrease,748.584991,43.269958
2016-02-04,727.000000,701.859985,722.809998,708.010010,5168700,708.010010,Decrease,715.410004,14.799988
2016-02-05,703.989990,680.150024,703.869995,683.570007,5105700,683.570007,Decrease,693.720001,20.299988
2016-02-08,684.030029,663.059998,667.849976,682.739990,4247400,682.739990,Increase,675.294983,14.890015
2016-02-09,699.900024,668.770020,672.320007,678.109985,3608900,678.109985,Increase,675.214996,5.789978
2016-02-10,701.309998,682.130005,686.859985,684.119995,2638000,684.119995,Decrease,685.489990,2.739990
2016-02-11,689.349976,668.867981,675.000000,683.109985,3024000,683.109985,Increase,679.054993,8.109985
2016-02-12,693.750000,678.599976,690.260010,682.400024,2141400,682.400024,Decrease,686.330017,7.859985
2016-02-16,698.000000,685.049988,692.979980,691.000000,2520000,691.000000,Decrease,691.989990,1.979980
2016-02-17,709.750000,691.380005,698.090027,708.400024,2492600,708.400024,Increase,703.245026,10.309998
2016-02-18,712.349976,696.030029,710.000000,697.349976,1883200,697.349976,Decrease,703.674988,12.650024
2016-02-19,703.080994,694.049988,695.030029,700.909973,1589300,700.909973,Increase,697.970001,5.879944
2016-02-22,713.239990,702.510010,707.450012,706.460022,1949800,706.460022,Decrease,706.955017,0.989990
2016-02-23,708.400024,693.580017,701.450012,695.849976,2009300,695.849976,Decrease,698.649994,5.600037
2016-02-24,700.000000,680.780029,688.919983,699.559998,1963600,699.559998,Increase,694.239990,10.640015
2016-02-25,705.979980,690.585022,700.010010,705.750000,1642200,705.750000,Increase,702.880005,5.739990
2016-02-26,713.429993,700.859985,708.580017,705.070007,2243500,705.070007,Decrease,706.825012,3.510010
2016-02-29,710.890015,697.679993,700.320007,697.770020,2481100,697.770020,Decrease,699.045013,2.549988
2016-03-01,718.809998,699.770020,703.619995,718.809998,2151400,718.809998,Increase,711.214996,15.190002
2016-03-02,720.000000,712.000000,719.000000,718.849976,1629000,718.849976,Decrease,718.924988,0.150024
2016-03-03,719.450012,706.020020,718.679993,712.419983,1958000,712.419983,Decrease,715.549988,6.260010
2016-03-04,716.489990,706.020020,714.989990,710.890015,1972100,710.890015,Decrease,712.940002,4.099976
2016-03-07,708.091003,686.900024,706.900024,695.159973,2985100,695.159973,Decrease,701.029999,11.740051
2016-03-08,703.789978,685.340027,688.590027,693.969971,2076300,693.969971,Increase,691.279999,5.379944
2016-03-09,705.679993,694.000000,698.469971,705.239990,1421500,705.239990,Increase,701.854980,6.770020
2016-03-10,716.440002,703.359985,708.119995,712.820007,2833500,712.820007,Increase,710.470001,4.700012

In [6]:
df[df["Status"]=="Increase"]["Middle"]

Date
2015-11-02    716.084991
2015-11-03    720.509979
2015-11-04    725.054993
2015-11-05    730.359985
2015-11-06    732.630005
2015-11-10    726.360016
2015-11-11    733.930023
2015-11-12    731.114990
2015-11-16    722.279999
2015-11-18    733.790009
2015-11-20    751.565002
2015-11-25    748.145020
2015-11-27    749.360016
2015-12-01    757.074982
2015-12-04    759.954987
2015-12-08    760.130005
2015-12-14    744.779999
2015-12-16    754.045013
2015-12-21    746.950012
2015-12-28    757.714996
2015-12-29    771.644989
2016-01-06    736.809998
2016-01-12    723.875000
2016-01-14    710.049988
2016-01-15    693.369995
2016-01-20    693.529999
2016-01-21    704.385010
2016-01-22    724.424988
2016-01-28    726.589996
2016-01-29    737.240021
2016-02-01    751.230011
2016-02-08    675.294983
2016-02-09    675.214996
2016-02-11    679.054993
2016-02-17    703.245026
2016-02-19    697.970001
2016-02-24    694.239990
2016-02-25    702.880005
2016-03-01    711.214996
2016-03-08    691.279999
2016-03-09    701.854980
2016-03-10    710.470001
Name: Middle, dtype: float64

In [7]:
p=figure(x_axis_type="datetime", width=1000, height=300, sizing_mode="scale_width")
p.title.text="Candlestick Chart"
p.grid.grid_line_alpha=0.3

p.segment(df.index,df.High,df.index,df.Low,color="black")

p.rect(x=df.index[df["Status"]=="Increase"],y=df[df["Status"]=="Increase"]["Middle"],width=hours_12,height=df[df["Status"]=="Increase"]["Height"],fill_color='#CCFFFF',line_color="black")

p.rect(x=df.index[df["Status"]=="Decrease"],y=df[df["Status"]=="Decrease"]["Middle"],width=hours_12,height=df[df["Status"]=="Decrease"]["Height"],fill_color='#FF3333',line_color="black")

output_file("stock.html")
# show(p)

In [8]:
script, div = components(p)
cdn_js=CDN.js_files
cdn_css=CDN.css_files

In [9]:
cdn_js

['https://cdn.pydata.org/bokeh/release/bokeh-1.3.1.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.1.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.1.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-gl-1.3.1.min.js']

In [10]:
cdn_css

[]